### ISSUE TITLE
TypeError: context.resume is not a function

### ISSUE THREAD

**Issue by joepdooper** [swevans/unmute#1]
Hi,

Thanks again for the great script, works great!

 In the console I get `TypeError: context.resume is not a function` on `unmute.js:62:29` on every click / mousedown / touch. On the minified version as `TypeError: i.resume is not a function`.

**Comment by swevans** [comment]
The error you're seeing indicates that whatever object was passed to unmute is not a real AudioContext instance.

```javascript
// Create an audio context instance
let context = new (window.AudioContext || window.webkitAudioContext)();
// Pass it to unmute
unmute(context);
```

**Questions**
1. What device and browser?
2. Are you using any other audio frameworks? ie: howler
3. Are you using any polyfills for web audio or polyfill frameworks? ie: modernizr

**My Hunch**
Any one of these:
- You may accidentally be passing the wrong thing to unmute
- The browser / device environment doesn't support window.AudioContext || window.webkitAudioContext. Some don't Sadly. [](https://caniuse.com/#feat=audio-api)
- AudioContext / webkitAudioContext is being polyfilled by some default constructor function that doesn't follow the real WebAudio API.

Want to post a little more code? It would be really helpful to see code where you create the AudioContext instance and pass it to unmute.

**Comment by joepdooper** [comment]
@swevans thank you for your reply… and I think the answer to my question; I will test it ASAP.

In [sketch.js](https://raw.githubusercontent.com/joepdooper/p5js-soundcloud-player/master/js/sketch.js) is the whole script.

There you can find `sound = loadSound('unmute.mp3'); unmute(sound);` in a preload which does its work. Afterwards the `sound` variable is still in use to load audio from the SoundCloud API. I think I should change it to `unmutesound = loadSound('unmute.mp3'); unmute(unmutesound);` which afterwards won't be used anymore.

**Comment by swevans** [comment]
Where is loadSound defined?

What is the return type?

What is unmute.mp3? You shouldn't need a special sound for unmute.

Where is getAudioContext defined?

I believe that you may be passing the wrong thing to unmute. I am guessing that loadSound is returning an instance of a WebAudioBuffer or a SourceNode. See: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

I noticed that somewhere else in the file you're using the function getAudioContext(). I am guessing that will return the instance of the audio context. You need to pass that to unmute, and you only ever have to pass it once. 

On that note, I don't think your touchStarted function shouldn't be necessary. unmute.js should be taking care of that for you once it is set up properly.

**Comment by joepdooper** [comment]
> Where is loadSound defined?
- It is a function within the p5.js Library

> What is unmute.mp3? You shouldn't need a special sound for unmute.
- It is an empty MP3 file for me to start the unmute. It didn't work with the audio from the SoundCloud API.

> I noticed that somewhere else in the file you're using the function getAudioContext(). I am guessing that will return the instance of the audio context. You need to pass that to unmute, and you only ever have to pass it once.
- Thanks, I'll look into that!

Thanks again for the help!

**Comment by swevans** [comment]
You just need to do this:
```javascript
// AFTER p5.sound.js AND unmute.js have finished loading..
if (getAudioContext()) unmute(getAudioContext());
```

You shouldn't need to load an unmute.mp3 sound, and you definitely don't want to pass that to the unmute function. Unmute already loads a super-short, silent mp3 file using a data url embedded in unmute.js.

You also **shouldn't** need to do this:
```javascript
//Touch
function touchStarted() {
  if (getAudioContext().state !== 'running') {
    getAudioContext().resume();
  }
}
```
unmute will take care of that for ya.

Lastly, I should throw out a disclaimer that I am not sure what p5 is doing under the hood. It will _probably_ work with unmute. But I make no guarantee. :)

**Comment by joepdooper** [comment]
I changed my code to `unmutesound = loadSound('unmute.mp3'); unmute(unmutesound);` which I thought solved the console  error, but at the end didn't.

This didn't work for me…
```javascript
// AFTER p5.sound.js AND unmute.js have finished loading..
if (getAudioContext()) unmute(getAudioContext());
```
…but I should dig deeper propably.

And for some strange reason I need this code…
```javascript
//Touch
function touchStarted() {
  if (getAudioContext().state !== 'running') {
    getAudioContext().resume();
  }
}
```
…for it to work on my mobile.

But I only tested this with an "older" version of p5, I'll test it on an updated version of the website soon and will let you know. I'll have to play around.

Thank you so much for your time and help!

**Comment by swevans** [comment]
The touchStarted function is required for you on mobile right now because unmute _isn't_ set up properly.

What error / behavior are you seeing when you try this code?
```javascript
// AFTER p5.sound.js AND unmute.js have finished loading..
if (getAudioContext()) unmute(getAudioContext());
```

**Comment by joepdooper** [comment]
> What error / behavior are you seeing when you try this code?

I get "ReferenceError: getAudioContext is not defined".

**Comment by swevans** [comment]
Sounds like p5.sound.js isn't loaded yet or isn't imported or something.

**Comment by joepdooper** [comment]
This fixed it:

```javascript
function touchStarted() {
  if (getAudioContext().state !== 'running') {
    unmute(getAudioContext());
  }
}
```

**Comment by swevans** [comment]
@joepdooper I'm guessing your touchStarted function is called on every touch start, correct?

If so, you should add a variable to make sure you don't call unmute(getAudioContext()); more than once. Calling unmute more than once will cause multiple instances of the unmute controller to run. That could cause performance issues over time.

Something like this should do the trick.


```javascript
var unmuteStarted = false;
function touchStarted() {
  if (unmuteStarted == false && getAudioContext.state !== 'running') {
    unmuteStarted = true;
    unmute(getAudioContext());
  }
}
```

**Comment by joepdooper** [comment]
I changed it! Thank you so much!
