### ISSUE TITLE
Huge Thanks, capacitor v3 + stenciljs work in silent mode

### ISSUE THREAD

**Issue by numerized** [swevans/unmute#4]
Man, you made my capacitor v3 / stenciljs music generation app able to work in silent mode.
On top of that when I use your other unmute-no-pause version I can add background mode.
I'll work on making WebAudio interact with native audio iOS control center and report here.
You saved many headaches and hours of useless work.
I'll buy you a pizza.

**Comment by swevans** [comment]
So happy to hear it! That is exciting. I'm going to close this issue out. Thanks for the pizza!
