### ISSUE TITLE
Destroying channel tag leads to /null request

### ISSUE THREAD

**Issue by yomed** [swevans/unmute#7]
Hi again. I've been using this recently on a project, and noticed that there was uptick in requests to `/null` on my server. From digging in the code, it looks like this is caused by `destroyChannelTag()`. I can repro by creating an audio tag and setting it's `src` to `null` like in the code.
https://github.com/swevans/unmute/blob/3c6b03ed863afe916a34dd0f920feadd57aa7b6c/dev/src/unmute.ts#L240-L249

It seems mostly harmless, but wanted to check if you've seen this, and if you had other ideas on workarounds to hide the playback controls.

**Comment by swevans** [comment]
Hey! Thanks for bringing this to my attention and nice catch. It makes sense the browser is trying to load ./null into the channel tag. This happens whenever unmute needs to *completely stop* the "channel controller tag"  to hide the native audio playback controls. I Just pushed a change that instead sets the src to "about:blank". This will cause a network error (which is desirable to hide the native playback controls)... but at least it only runs on iOS and won't cause any unnecessary requests to your server.

RE: more ideas on hiding the native controls- Sorry I don't have any other ideas. I have been fighting this issue for like 6 years on iOS and its only gotten more challenging to overcome. Pausing and setting the <audio> tag src to something invalid is the best I have come up with. Unfortunately it has the side effect of web audio playback switching back to the ringer channel. Hence why unmute suspends the web audio context whenever the app / tab moves to the background.

Let me know how this works out for ya!

**Comment by yomed** [comment]
Got it, interesting workaround. And good idea to use `about:blank`, that works great!
